POST http://localhost:3001/api/notes 
Content-Type: application/json

{
    "content": "testing a post",
    "important": false
}

###

POST http://localhost:3001/api/notes 
Content-Type: application/json

{

}